services:
  db:
    image: mysql:8.0
    container_name: employee-management-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abishek10  
      MYSQL_DATABASE:   employee_management       
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./server
    container_name: employee-management-backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root                  
      DB_PASSWORD: abishek10    
      DB_NAME: employee_management           
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
    container_name: employee-management-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

volumes:
  db_data:


      